[workspace]

[package]
name = "oxml-json-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.oxml-json]
path = ".."

[profile.release]
debug = true
debug-assertions = true
overflow-checks = true

[[bin]]
name = "parse"
path = "fuzz_targets/parse.rs"
test = false
doc = false
